### ISSUE TITLE
What is the score behind % in the all_sim_ontology.txt file?

### ISSUE THREAD

**Issue by bali-eng** [y95847frank/Joint-Retrofitting#1]
Hello,
I am trying to use your code. I have a small question. What is the score behind %?
As an example, renew%0#0.6, 0.6 is the weigh, and what is 0?

Thanks in advance

**Comment by y95847frank** [comment]
The number behind % represents its sense. For instance, if “bank” has two senses, which are related to money and river respectively, then “bank%01” will be the sense vector close to money. “And, bank%02” is the vector related to river.

**Comment by bali-eng** [comment]
Thank you.
